### ISSUE TITLE
Support for alternative DB drivers

### ISSUE THREAD

**Issue by mszabo-wikia** [zapodot/embedded-db-junit#13]
Hello. First of all, thank you for your awesome plugin, it's of great help when it comes to DAO layer integration testing (as you described in the use cases).

However a shortcoming of the H2 database system is its limited support for RDBMS specific syntaxes like MySQL's `INSERT ... ON DUPLICATE KEY UPDATE`, so it is not possible to use these useful features in applications if H2 is used to test it. Alternative in-memory databases such as HSQLDB are [better off](http://hsqldb.org/doc/2.0/guide/compatibility-chapt.html#coc_compatibility_mysql) in that regard.

As such, it might be desirable to provide a way for developers to use a different DB driver to power the test rule. Do you think this would be feasible, or would this be out of scope for this project?

**Comment by zapodot** [comment]
Thanks @TK-999 for a good suggestion. I will look into hsqldb integration in future releases

**Comment by zapodot** [comment]
Completed on the master branch. Will be released as part of the 1.1 release

**Comment by zapodot** [comment]
@mszabo-wikia The 1.1.0 release which includes this feature is now available in Maven central. Thank you for adding this feature request

**Comment by mszabo-wikia** [comment]
Thank you!
