### ISSUE TITLE
Support for loading from multiple SQL scripts is broken

### ISSUE THREAD

**Issue by zapodot** [zapodot/embedded-db-junit#35]
Because of how it was implemented as a solution for issue #14, the EmbeddedDatabaseRule may only invoke a single instance of each type of initialization plugin (as commented by  @andham).

**Comment by andham** [comment]
Great, thanks!

**Comment by zapodot** [comment]
> Great, thanks!

No problem! Thank you for reporting this bug. I have now released v. 1.1.2 which contains this fix. It should be available from Maven central shortly

**Comment by andham** [comment]
I noticed that and has already upgraded. Works just fine now. Awesome, you made my day!
