### ISSUE TITLE
Use mockito 2.x and byte-buddy 1.x

### ISSUE THREAD

**Issue by victornoel** [zapodot/embedded-db-junit#4]
Hi,

I'm not sure it is in your plan to use the latest Mockito (and thus byte-buddy, which is the reason I originally wanted to open this issue), but basically, embedded-db-junit can't be used with Mockito 2.x because of API changes in byte-buddy since 1.x..

**Comment by zapodot** [comment]
Ok. Will look into that. Thanks for reporting back :-)

**Comment by zapodot** [comment]
V. 0.8 containing updated versions of Mockito and Bytebuddy has now been released to Maven Central and it should be available i a few hours

**Comment by victornoel** [comment]
thanks! it works well now :)
