### ISSUE TITLE
DB not reset after the test

### ISSUE THREAD

**Issue by victornoel** [zapodot/embedded-db-junit#5]
When using an  `EmbeddedDatabaseRule` as a `@Rule,` I would expect to have a fresh empty database for each test of my test class, but apparently, it is the same database used in all of the tests.

I guess the problem is that h2 does keep the database in memory even if you close the connection.

**Comment by zapodot** [comment]
In theory it should make a new database for every test unless you add a name to the DataSource explicitly using the fluent builder. I will add some tests to find out what's happening here. Thx for reporting :+1:

**Comment by victornoel** [comment]
Actually I am using a name in the fluent builder :)

**Comment by zapodot** [comment]
So you should probably stop doing that :-)

14. nov. 2016 6.18 p.m. skrev "Victor Noël" <notifications@github.com>:

**Comment by victornoel** [comment]
I will need to find an alternative, because the thing I am testing is taking the jdbc url from a file, so I thought (until now, I will look if I can) that I had to choose a fixed name for the h2 in-memory database.

I guess this issue could be closed? Or maybe this could be documented before it is... Thanks :)

**Comment by victornoel** [comment]
I managed to make it work as expected :)
