### ISSUE TITLE
Incoherence of behaviour between getConnection and getConnectionJdbcUrl with liquibase plugin?

### ISSUE THREAD

**Issue by victornoel** [zapodot/embedded-db-junit#7]
Sorry, this is maybe just a question and not a bug, but I simply can't make embedded-db-junit with dropwizard database subsystem.

Basically, in my test I have the following:
```java
public class UserSessionTest {

    public static final User ADMIN = new User("admin", "Administrator", null);

    public static class App extends CockpitApplication<CockpitConfiguration> {
        // only needed because of generics
    }

    @ClassRule
    public static final EmbeddedDatabaseRule dbRule = EmbeddedDatabaseRule.builder()
            .initializedByPlugin(LiquibaseInitializer.builder().withChangelogResource("migrations.xml").build())
            .initializedByPlugin(new InitializationPlugin() {
                @Override
                public void connectionMade(@Nullable String name, @Nullable Connection connection) {
                    try (DSLContext using = DSL.using(connection, SQLDialect.H2)) {
                        using.insertInto(Tables.USERS).set(new UsersRecord(ADMIN.username,
                                new BCryptPasswordEncoder().encode(ADMIN.username), ADMIN.name, ADMIN.lastWorkspace))
                                .execute();
                    }
                }
            }).build();

    @Rule
    public final DropwizardAppRule<CockpitConfiguration> appRule = new DropwizardAppRule<>(App.class,
            ResourceHelpers.resourceFilePath("user-session-tests.yml"),
            ConfigOverride.config("database.url", () -> dbRule.getConnectionJdbcUrl()));

    ....
}
```

And while the initialisation of the database with the two plugins works nicely, the SQL query made from dropwizard (I am using dropwizard-jooq with dropwizard-db, which setups a JDBC pool) returns no row.

For example, I even tried putting the following in my dropwizard `Application.run()` method (the configuration, I verified, is correctly referring to the embedded database JDBC URL):
```java
        System.out.println(DSL.using(jooqConf).selectFrom(Tables.USERS).fetch());
```
And it says there is zero rows, while if I put the same thing in the test method itself, then it shows me the rows inserted by the plugin…

Either I am doing something wrong, or there is maybe a problem with the connections or maybe a transaction not committed or I don't know what… The only specific thing I can think of is that everything executed directly from the test class itself is done with the connections built by embedded-db-junit and not built directly from the JDBC URL string…

Hope it's ok to ask that here :)

**Comment by victornoel** [comment]
Actually it may not be related to dropwizard at all.

If in my test class, I write the following:
```java
        String url = dbRule.getConnectionJdbcUrl();
        System.out.println("with " + url + ":\n" + DSL.using(url).selectFrom(Tables.USERS).fetch());
        System.out.println("with connection:\n" + DSL.using(dbRule.getConnection()).selectFrom(Tables.USERS).fetch());
```

The first will return no row while the second will return the correct information:
with jdbc:h2:mem:UserSessionTest:
```
+--------+--------+----+--------------+
|USERNAME|PASSWORD|NAME|LAST_WORKSPACE|
+--------+--------+----+--------------+
with connection:
+--------+--------------------------------------------------+-------------+--------------+
|USERNAME|PASSWORD                                          |NAME         |LAST_WORKSPACE|
+--------+--------------------------------------------------+-------------+--------------+
|admin   |$2a$10$uiBa4pHjNf/PVQOtjx4nreUPWJo2i0564hD7zNMw...|Administrator|        {null}|
+--------+--------------------------------------------------+-------------+--------------+
```

I am expecting things to work the same using the connection or using the url… but maybe I am making a wrong assumption here? Thanks :)

**Comment by victornoel** [comment]
Only way I could find to make it work is to use the JDBC URL when inserting the test data:
```java
    @ClassRule
    public static final EmbeddedDatabaseRule dbRule = EmbeddedDatabaseRule.builder()
            .initializedByPlugin(LiquibaseInitializer.builder().withChangelogResource("migrations.xml").build())
            .initializedByPlugin(new InitializationPlugin() {
                @Override
                public void connectionMade(@Nullable String name, @Nullable Connection connection) {
                    try (DSLContext using = DSL.using(dbRule.getConnectionJdbcUrl())) {
                        using.insertInto(Tables.USERS).set(new UsersRecord(ADMIN.username,
                                new BCryptPasswordEncoder().encode(ADMIN.username), ADMIN.name, ADMIN.lastWorkspace))
                                .execute();
                    }
                }
            }).build();
```

Surprisingly, initialising the schema does not need this, it simply use the connection and the schema is correctly present when accessing the db with the JDBC URL.

**Comment by zapodot** [comment]
Hi @victornoel and thank you for your report (and patience). I do believe that this may be a bug in how the library constructs the connection URL. If you have a test case it would be neat if you could provide a gist or something 👍

**Comment by victornoel** [comment]
Ok, here it is: https://gist.github.com/victornoel/bef5ac4e037949594210b8ccf5779d6d

Apparently it only happens with the liquibase plugin (I couldn't reproduce it if I created the table via `withInitialSql`).

Thanks!

**Comment by victornoel** [comment]
Opened also #8 that I discovered while doing my test, I don't know if there is some link...

**Comment by zapodot** [comment]
Unless someone proves me wrong, I will close this issue shortly :-)

**Comment by victornoel** [comment]
@zapodot as long as the tests I provided pass with latest master, I'm good with it :)

**Comment by zapodot** [comment]
@victornoel  Tried to run the tests from the GIST you provided and all tests were green except for "failsButShouldnt". 
After a little bit of debugging I found out that while the both connections connected to the same instance of the database they open two different sessions. As the insert statement did not commit the transaction the  inserted record was not available for the new session that was opened by the DriverManager. This is probably due to transaction isolation (even though auto-commit was enabled). Adding an explicit commit after the insert statement made the test green again.

**Comment by victornoel** [comment]
I see, that's funny, but I guess that's how JDBC work, so in the end, it seems that my bug wasn't really a bug!

Thanks for the final explanation (and closure ;).
