### ISSUE TITLE
Should the Connection given to InitializationPlugin be Closeable?

### ISSUE THREAD

**Issue by victornoel** [zapodot/embedded-db-junit#8]
I understood that `InitializationPlugin.getConnection()` returned `Connection that` couldn't be closed for the duration of the test.

But I noticed that when implementing `InitializationPlugin.connectionMade`, the `Connection` that was passed to it could be closed.

Is that on purpose? Could it be the reason behind #7?

**Comment by zapodot** [comment]
Hi again @victornoel and thank you for reporting back this issue. You were right to assume that this was indeed a bug. For the sake of consistency the InititializationPlugin should be given the same sort of connection as is provided to the tests. I have created a fix and will push it shortly. It should also solve #7, but keeps it open until you have confirmed it.

**Comment by zapodot** [comment]
Just released this fix as part of version 1.0-RC1. If no new major issues appear you can expect a 1.0 release in a few weeks.
